### ISSUE TITLE
hope add x.47 version support

### ISSUE THREAD

**Issue by ylq5126** [starburstdata/metabase-driver#106] opened 2023-08-22 02:27 UTC
metabase x.47 timestamp field not support

**Comment by MohsenIT** [comment] 2023-09-18 09:39
We cannot filter of aggregate on any datetime field (on Trino Catalogs only) in the last version using Metabase UI (Question), while native query is possible yet.
The error:
`Wrong number of args (1) passed to: metabase.query-processor.timezone/report-timezone-id-if-supported`

**Comment by lpoulain** [comment] 2023-09-19 14:47
@MohsenIT please file a separate issue with details on how to reproduce this, because I was not able to get such an error

**Comment by marcpearson** [comment] 2023-09-19 19:04
I receive the same error with metabase 0.47.X. when filtering any date/timestamp field. Maybe it as something to do with this https://www.metabase.com/docs/latest/developers-guide/driver-changelog

My Trino installlation have multiples types of catalog SQLServer and MySQL. But the query doesn't pass metabase because the Trino Web UI don't show any running query.

I receive the same error message when in the metabase query wizard (after added a date filter...) i click the button to view the raw SQL query... the popup contain the error : wrong number of args (1) ....

Metabase is configure with America/New_York for timezone reporting

**Comment by lpoulain** [comment] 2023-09-19 23:46
Got it, I was *finally* able to reproduce this issue. Let me look at this.

**Comment by lpoulain** [comment] 2023-09-20 00:17
@marcpearson the deprecated API mentioned in the link you gave have actually nothing to do with this error. For some reason the Metabase `report-timezone-id-if-supported` API has changed and I cannot find any documentation about it.

It's still useful information as some API will be removed with Metabase 0.50.0.

**Comment by MohsenIT** [comment] 2023-09-20 05:42
I try to show when bug appears.
### 1. filter variable on date column
the native query run correctly:
![Screenshot from 2023-09-20 08-39-17](https://github.com/starburstdata/metabase-driver/assets/31584590/c8272fe7-f062-480a-bec2-6c46c1f4d4fe)
but when change filter to UI variable:
![Screenshot from 2023-09-20 08-38-00](https://github.com/starburstdata/metabase-driver/assets/31584590/007fa0b7-8d58-4753-be6c-708050c81066)

**Comment by MohsenIT** [comment] 2023-09-20 05:56
### filter on a column
1. load a table
![image](https://github.com/starburstdata/metabase-driver/assets/31584590/90dffadb-2ebf-45b0-9dc1-6155fa14dbbf)
2. filter on date column using UI
![image](https://github.com/starburstdata/metabase-driver/assets/31584590/b8aee4d2-354f-4224-a3e0-02b6a458cffe)
3. error:
![image](https://github.com/starburstdata/metabase-driver/assets/31584590/a3ed3ea4-6ddf-4806-97e8-6b812736568c)

**Comment by MohsenIT** [comment] 2023-09-20 05:58
> @marcpearson the deprecated API mentioned in the link you gave have actually nothing to do with this error. For some reason the Metabase `report-timezone-id-if-supported` API has changed and I cannot find any documentation about it.
> 
> It's still useful information as some API will be removed with Metabase 0.50.0.

Filtering on date-time column is a very useful use-case. Any other solution?

**Comment by lpoulain** [comment] 2023-09-20 13:26
@MohsenIT Metabase 0.50 has nothing to do with the current error. I am working on a fix for the datetime filter.

**Comment by marcpearson** [comment] 2023-09-22 15:29
Any development for the fix ...the pull request seem to be stalled with failing tests

**Comment by lpoulain** [comment] 2023-09-22 15:37
It turns out that the upgrade to 0.47.x is more complex than expected, as more than one API changed with that version. Working to understand why are the tests failing now.

**Comment by MohsenIT** [comment] 2023-09-27 03:17
@lpoulain Thanks for your follow up. Is there any good news about resolving this problem?
We have daily reporting this issue from our users. At first, we try to revert Metabase x.47 update, but reverting caused several other issues. The only way we have now is to solve this metabase-driver issue.

**Comment by lpoulain** [comment] 2023-09-27 04:25
@MohsenIT I believe I was able to fix the issue. The PR is in its review stage right now.

**Closed** 2023-09-27 18:42 UTC

**Comment by lpoulain** [comment] 2023-09-27 22:20
The Metabase Driver 4.0.0 (which contains the fix for this issue) has been released.

**Comment by marcpearson** [comment] 2023-09-28 12:47
Thank you very much. Very appreciate

**Comment by lpoulain** [comment] 2023-09-28 13:54
Pas de problème ;-)

**Comment by MohsenIT** [comment] 2023-09-30 03:49
I wanted to express my gratitude for your support . Thanks a lot.
