### ISSUE TITLE
Add feature to see all trino catalog in metabase catalog database connection

### ISSUE THREAD

**Issue by AfrouzMashayekhi** [starburstdata/metabase-driver#103] opened 2023-07-12 12:18 UTC
When adding a Trino cluster connection to metabase with starburst driver, you have to choose one catalog which limits Trino functionality to filter dashboards and queries to one catalog and you can't use another catalog data (which you joined in the query with the default catalog) to filter and choose variables.

**Comment by andrewdibiasio6** [comment] 2024-02-14 16:42
This is a duplicate of https://github.com/starburstdata/metabase-driver/issues/38 closing.

**Closed by andrewdibiasio6** 2024-02-14 16:42 UTC
